name: Build

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * 1'

env:
  version: '3.0'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Create tarball for Azure Linux ${{ env.version }}
        run: |
          set -ex
          podman run --name=cont -di mcr.microsoft.com/azurelinux/base/core:${{ env.version }}
          podman exec cont tdnf upgrade -y
          podman exec cont tdnf install util-linux shadow-utils -y
          podman exec cont tdnf clean all
          podman exec cont pwconv
          podman exec cont grpconv
          podman exec cont chmod 0744 /etc/shadow
          podman exec cont chmod 0744 /etc/gshadow
          podman exec cont bash -c 'echo nameserver 208.67.222.222 > /etc/resolv.conf'
          podman export -o distro.tar cont
          podman kill cont
          podman rm cont
      - name: Package
        run: |
          set -ex
          zip pkg.zip distro.tar install.cmd 
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.date.outputs.date }}
          name: Build on ${{ steps.date.outputs.date }}
          files: |
            pkg.zip
